version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: food_service
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: foodservice
      MYSQL_PASSWORD: foodservice
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
